version: '3'

services:
  api:
    container_name: werkstuk_api
    build: './api'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: werkstuk_dev
      POSTGRES_HOST: werkstuk_db
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/workdir/src
      - ./api/uploads:/workdir/videos
  db:
    container_name: werkstuk_db   
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: werkstuk_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432